FROM public.ecr.aws/lambda/python:3.14
 
# Copy requirements and install dependencies
COPY pyproject.toml README.md LICENSE ./
COPY src/drillapi ${LAMBDA_TASK_ROOT}/drillapi
COPY tests ${LAMBDA_TASK_ROOT}/tests
 
RUN pip install --no-cache-dir -e .
 
# Set the CMD to your handler
CMD ["drillapi.lambda_handler.handler"]